server:
  port: 5000
security:
  oauth2:
    client:
      clientId: jjh
      clientSecret: jjh
      accessTokenUri: http://localhost:3000/oauth/token
      userAuthorizationUri: http://localhost:3000/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      token-info-uri: http://localhost:3000/oauth/check_token
spring:
  thymeleaf:
    cache: false